/* Generated By:JavaCC: Do not edit this line. CircuitParserConstants.java */
package GCParser;

public interface CircuitParserConstants {

  int EOF = 0;
  int COLON = 4;
  int PERIOD = 5;
  int COMMA = 6;
  int LINE_ENDING = 7;
  int OPEN_PAREN = 8;
  int CLOSE_PAREN = 9;
  int INPUT_MARK = 10;
  int OUTPUT_MARK = 11;
  int SIGNED_MARK = 12;
  int INCLUDE = 13;
  int VERSION = 14;
  int UNSIGNED_MARK = 15;
  int START_PARTY = 16;
  int END_PARTY = 17;
  int PATH = 18;
  int IDENTIFIER = 19;
  int INTEGER = 20;
  int COMMENT = 21;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\":\"",
    "\".\"",
    "\",\"",
    "\"\\n\"",
    "\"(\"",
    "\")\"",
    "\".input\"",
    "\".output\"",
    "\"signed\"",
    "\".include\"",
    "\".version\"",
    "\"unsigned\"",
    "\".startparty\"",
    "\".endparty\"",
    "<PATH>",
    "<IDENTIFIER>",
    "<INTEGER>",
    "<COMMENT>",
  };

}
